-- Pope Pius Portal central cloud storage
-- Run once in Supabase Dashboard -> SQL Editor -> New query.

create extension if not exists pgcrypto;

create table if not exists public.portal_health_check (
  id bigint generated by default as identity primary key,
  service_name text not null unique,
  checked_at timestamptz not null default now()
);

insert into public.portal_health_check(service_name)
values ('student-diary-portal')
on conflict (service_name) do update set checked_at = now();

create table if not exists public.portal_state (
  state_key text primary key check (state_key ~ '^pius_[A-Za-z0-9_.:+-]{1,180}$'),
  state_value jsonb not null default 'null'::jsonb,
  version bigint not null default 1 check (version > 0),
  updated_by text not null default 'system',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists portal_state_updated_at_idx
  on public.portal_state(updated_at desc);

create table if not exists public.portal_audit_log (
  id uuid primary key default gen_random_uuid(),
  action text not null,
  entity_type text not null,
  entity_id text,
  actor text not null default 'system',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists portal_audit_created_at_idx
  on public.portal_audit_log(created_at desc);
create index if not exists portal_audit_entity_idx
  on public.portal_audit_log(entity_type, entity_id);

alter table public.portal_health_check enable row level security;
alter table public.portal_state enable row level security;
alter table public.portal_audit_log enable row level security;

-- No public policies are intentionally created. Browser clients cannot access
-- these tables directly. Only the Render server's service-role/secret key can
-- bypass RLS and read or write portal records.

insert into storage.buckets (id, name, public, file_size_limit)
values ('portal-private', 'portal-private', false, 52428800)
on conflict (id) do update set public=false;

-- Storage also remains private. Signed access/upload routes will be added to
-- the Render server in the document/media migration phase.

